### ISSUE TITLE
pxc-server not starting when using persistent storage

### ISSUE THREAD

**Issue by rafagsiqueira** [Flowman/docker-pxc#1]
Hello!
First of all thanks for your work on the rancher catalog PXC-Cluster! It is really handy!
And now for my issue.

Cluster starts fine except when using host mount or volume driver share with pxc-data volumes.

Following my docker-compose.yml:

`pxc-clustercheck:`
`image: flowman/percona-xtradb-cluster-clustercheck:v2.0`
`net: "container:pxc"`
`labels:`
`io.rancher.container.hostname_override: container_name`
`volumes_from:`
`- 'pxc-data'`
`pxc-server:`
`image: flowman/percona-xtradb-cluster:5.6.28-1`
`net: "container:pxc"`
`environment:`
`MYSQL_ROOT_PASSWORD: <pass>`
`PXC_SST_PASSWORD: <pass>`
`labels:`
`io.rancher.container.hostname_override: container_name`
`volumes_from:`
`- 'pxc-data'`
`entrypoint: bash -x /opt/rancher/start_pxc`
`pxc-data:`
`image: flowman/percona-xtradb-cluster:5.6.28-1`
`net: none`
`environment:`
`MYSQL_ALLOW_EMPTY_PASSWORD: "yes"`
`volumes:`
`- /data/mysql:/var/lib/mysql`
`- /etc/mysql/conf.d`
`- /docker-entrypoint-initdb.d`
`command: /bin/true`
`labels:`
`io.rancher.container.start_once: true`
`pxc:`
`image: flowman/percona-xtradb-cluster-confd:v0.2.0`
`labels:`
`io.rancher.sidekicks: pxc-clustercheck,pxc-server,pxc-data`
`io.rancher.container.hostname_override: container_name`
`io.rancher.scheduler.affinity:container_label_soft_ne:` `io.rancher.stack_service.name=$${stack_name}/$${service_name}`
`volumes_from:`
`- 'pxc-data'`
When I try using any persistent volume I get this error:

`03/08/2016 10:37:03MySQL init process done. Ready for start up.`
`03/08/2016 10:37:03`
`03/08/2016 10:37:042016-08-03 13:37:04 0 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.`
`03/08/2016 10:37:042016-08-03 13:37:04 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).`
`03/08/2016 10:37:042016-08-03 13:37:04 0 [Note] mysqld (mysqld 5.6.28-76.1-56) starting as process 1 ...`
`03/08/2016 10:37:052016-08-03 13:37:05 1 [Note] WSREP: Read nil XID from storage engines, skipping position init`
`03/08/2016 10:37:052016-08-03 13:37:05 1 [Note] WSREP: wsrep_load(): loading provider library '/usr/lib/libgalera_smm.so'`
`03/08/2016 10:37:052016-08-03 13:37:05 1 [Note] WSREP: wsrep_load(): Galera 3.14(r53b88eb) by Codership Oy <info@codership.com> loaded successfully.`
`03/08/2016 10:37:052016-08-03 13:37:05 1 [Note] WSREP: CRC-32C: using hardware acceleration.`
`03/08/2016 10:37:052016-08-03 13:37:05 1 [Note] WSREP: Found saved state: 00000000-0000-0000-0000-000000000000:-1`
`03/08/2016 10:37:052016-08-03 13:37:05 1 [ERROR] WSREP: Failed to open file '/var/lib/mysql//galera.cache': 1 (Operation not permitted)`
`03/08/2016 10:37:05     at galerautils/src/gu_fdesc.cpp:constructor_common():138`
`03/08/2016 10:37:052016-08-03 13:37:05 1 [ERROR] WSREP: wsrep::init() failed: 7, must shutdown`
`03/08/2016 10:37:052016-08-03 13:37:05 1 [ERROR] Aborting`
`03/08/2016 10:37:05`
`03/08/2016 10:37:052016-08-03 13:37:05 1 [Note] Binlog end`
`03/08/2016 10:37:052016-08-03 13:37:05 1 [Note] mysqld: Shutdown complete`

And then PXC-server instance stops.

**Comment by Flowman** [comment]
Hi @rafagsiqueira sorry for a late answer

Here is a example of my config with persistent storage, and I use Ubuntu 15.10. 

I don't get the same issue as you.

```yaml
pxc-data:
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.start_once: 'true'
    io.rancher.scheduler.affinity:host_label: db=true
  command:
  - /bin/true
  image: flowman/percona-xtradb-cluster:5.6.28-1
  volumes:
  - /docker-entrypoint-initdb.d
  - /etc/mysql/conf.d
  - /srv/docker/mysql:/var/lib/mysql
  net: none
pxc:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.sidekicks: pxc-data,pxc-server,pxc-clustercheck
    io.rancher.scheduler.affinity:host_label: db=true
    io.rancher.container.hostname_override: container_name
  image: flowman/percona-xtradb-cluster-confd:v0.2.0
  volumes_from:
  - pxc-data
pxc-server:
  environment:
    MYSQL_DATABASE: -
    MYSQL_PASSWORD: -
    MYSQL_ROOT_PASSWORD: -
    MYSQL_USER: -
    PXC_SST_PASSWORD: -
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: db=true
    io.rancher.container.hostname_override: container_name
  entrypoint:
  - bash
  - -x
  - /opt/rancher/start_pxc
  image: flowman/percona-xtradb-cluster:5.6.28-1
  volumes_from:
  - pxc-data
  net: container:pxc
pxc-clustercheck:
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: db=true
    io.rancher.container.hostname_override: container_name
  image: flowman/percona-xtradb-cluster-clustercheck:v2.0
  volumes_from:
  - pxc-data
  net: container:pxc
```
